---
    kind: pipeline
    type: docker
    name: default
    
    steps:
    - name: validate
      image: hashicorp/packer:light
      environment:
        AWS_ACCESS_KEY_ID:
          from_secret: AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY:
          from_secret: AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION:
          from_secret: AWS_DEFAULT_REGION
      commands:
        - packer validate -syntax-only packer.json
    
    volumes:
    - name: cache
      temp: {}
    